### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by leynier** [Edmartt/WebFlask-App#1]
https://github.com/wormholesepiol/flask-login/blob/92297f54038d7c5414a3bc3a299b101021485f5c/app/users.py#L25

Este método se debe eliminar para utilizar el de `UserMixin`.

Y en:

https://github.com/wormholesepiol/flask-login/blob/92297f54038d7c5414a3bc3a299b101021485f5c/app/users.py#L22

Debe ser `self.id = user[0]`

Luego implementar

```python
@staticmethod
def select_user_by_ud(id):
    cursor = db.connection.cursor()
    cursor.execute('SELECT * FROM users WHERE id="{}"'.format(id))
    user = cursor.fetchone()
    if user:
        id = user[0]
        username = user[1]
        password = user[2]
        email = user[3]
        result = User(password, email)
        result.id = id  # Debería modificarse el constructor de la clase User para poder pasarlo como parámetro opcional
        result.username = username  # Debería modificarse el constructor de la clase User para poder pasarlo como parámetro
        return result
```

Y finalmente en `load_user`:

```python
@login_manager.user_loader
def load_user(user_id):
    return User.select_user_by_ud(user_id)
```

**Comment by leynier** [comment]
Me equivoque en el nombre del método `select_user_by_ud`, debería llamarse `select_user_by_id` 😅

**Comment by leynier** [comment]
No se si esta perfecto el método `select_user_by_ud`, porque no he trabajado con esa forma de acceder a la base de datos. Pero el objetivo el método es obtener una instancia de la clase `User` mediante su `id`, entonces es hacer la consulta a la base de datos y con la respuesta obtenido construir una instancia de la clase de `User` y retornarla. Si el usuario no existe en la base de datos se debe retornar `None` (Esto se hace por defecto en las funciones de Python cuando no devuelven nada)

**Comment by Edmartt** [comment]
> No se si esta perfecto el método `select_user_by_ud`, porque no he trabajado con esa forma de acceder a la base de datos. Pero el objetivo el método es obtener una instancia de la clase `User` mediante su `id`, entonces es hacer la consulta a la base de datos y con la respuesta obtenido construir una instancia de la clase de `User` y retornarla. Si el usuario no existe en la base de datos se debe retornar `None` (Esto se hace por defecto en las funciones de Python cuando no devuelven nada)

Muchas gracias, Leynier, fuiste de gran ayuda.
